[dump1090]
host = "192.168.100.10"
port = 30003
timeout = 1.0

[regserver]
base_url = "http://localhost:5001"
cache_warm = "False"

[directories]
data = "data"
log = "log"
pid = "run"

[database]
dbname = "planes.db"

[logging]
logname = "plane.log"
scrapelog = "scrape_"


